apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- base
commonLabels:
  app.kubernetes.io/component: basic-auth-ingress
  app.kubernetes.io/instance: basic-auth-ingress-v0.7.0
  app.kubernetes.io/managed-by: kfctl
  app.kubernetes.io/name: basic-auth-ingress
  app.kubernetes.io/part-of: kubeflow
  app.kubernetes.io/version: v0.7.0
  kustomize.component: basic-auth-ingress
kind: Kustomization
namespace: istio-system
resources:
- overlays/managed-cert/cert.yaml
- overlays/application/application.yaml
